using Content.Client.UserInterface.Controls;
using Content.Shared._Polonium.CallablePhone;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Polonium.CallablePhone.UI;

[GenerateTypedNameReferences]
public sealed partial class CallablePhoneAdminCallPickupWindow : FancyWindow
{
    public event Action? Accepted;
    public event Action<string?>? Declined;

    public CallablePhoneAdminCallPickupWindow(string message)
    {
        RobustXamlLoader.Load(this);

        MessageLabel.Text = message;

        ReasonInput.IsValid = text => text.Length <= CentCommCallPickupResponseEvent.MaxRejectionReasonLength;

        ReasonCheckbox.OnToggled += _ =>
        {
            ReasonInput.Editable = ReasonCheckbox.Pressed;

            if (!ReasonCheckbox.Pressed)
                ReasonInput.Text = string.Empty;
        };

        AcceptButton.OnPressed += _ =>
        {
            Accepted?.Invoke();
            Close();
        };

        DeclineButton.OnPressed += _ =>
        {
            string? reason = null;

            if (ReasonCheckbox.Pressed && !string.IsNullOrWhiteSpace(ReasonInput.Text))
                reason = ReasonInput.Text.Trim();

            Declined?.Invoke(reason);
            Close();
        };

        OnClose += () =>
        {
            Accepted = null;
            Declined = null;
        };
    }
}
