// SPDX-FileCopyrightText: 2026 Maciej Walendziuk <ozzeusz@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared._Polonium.CallablePhone;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Polonium.CallablePhone.UI;

[GenerateTypedNameReferences]
public sealed partial class CallablePhoneAdminChatWindow : FancyWindow
{
    public NetEntity Phone { get; }

    public event Action<NetEntity, string>? MessageSubmitted;
    public event Action<NetEntity, string>? ImpersonationNameSubmitted;
    public event Action<NetEntity>? WindowClosed;

    public CallablePhoneAdminChatWindow(NetEntity phone, string title)
    {
        RobustXamlLoader.Load(this);

        Phone = phone;
        Title = title;

        ImpersonationRow.Visible = true;
        ImpersonationApply.OnPressed += OnImpersonationApplyPressed;
        Input.OnTextEntered += OnTextEntered;
        OnClose += () => WindowClosed?.Invoke(Phone);
    }

    private void OnImpersonationApplyPressed(BaseButton.ButtonEventArgs args)
    {
        ImpersonationNameSubmitted?.Invoke(Phone, ImpersonationInput.Text.Trim());
    }

    private void OnTextEntered(LineEdit.LineEditEventArgs args)
    {
        if (string.IsNullOrWhiteSpace(args.Text))
            return;

        MessageSubmitted?.Invoke(Phone, args.Text.Trim());
        Input.Clear();
    }

    public void ReceiveMessage(CallablePhoneAdminChatTextMessageEvent message)
    {
        var formatted = new FormattedMessage();

        if (message.IsLog)
        {
            formatted.PushColor(Color.FromHex("#aaaaaa"));
            formatted.AddText($"--- {message.Message} ---");
            formatted.Pop();
        }
        else
        {
            var color = message.Incoming ? Color.FromHex("#88ff88") : Color.FromHex("#ff8888");
            formatted.PushColor(color);
            formatted.AddText($"{message.Sender}: ");
            formatted.Pop();
            formatted.AddText(message.Message);
        }

        TextOutput.AddMessage(formatted);
    }

    public void SetInputEnabled(bool enabled)
    {
        Input.Editable = enabled;

        if (enabled)
            Input.GrabKeyboardFocus();
    }

    public void FocusInput()
    {
        if (Input.Editable)
            Input.GrabKeyboardFocus();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            MessageSubmitted = null;
            ImpersonationNameSubmitted = null;
            WindowClosed = null;
        }
    }
}

