using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Timing;

namespace Content.Client.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
public sealed partial class EntitySearchWindow : DefaultWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IClientConsoleHost _console = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public event Action? SearchRequested;
    public event Action? NextResultsRequested;

    private int _loadedCount;
    private TimeSpan _searchCooldownEnd = TimeSpan.Zero;

    public EntitySearchWindow(IDependencyCollection deps)
    {
        RobustXamlLoader.Load(this);
        deps.InjectDependencies(this);

        SearchButton.OnPressed += _ => TrySearch();
        SearchLineEdit.OnTextEntered += _ => TrySearch();
        NextButton.OnPressed += _ => NextResultsRequested?.Invoke();
    }

    public string SearchText => SearchLineEdit.Text;

    public void SetResults((string name, NetEntity entity)[] entities, bool hasNext)
    {
        _loadedCount = entities.Length;
        AdminEntityResultsList.Populate(ItemList, StatusLabel, entities, _console, _loc, hasNext);
        NextButton.Disabled = !hasNext;
    }

    public void AddResults((string name, NetEntity entity)[] entities, bool hasNext)
    {
        _loadedCount += entities.Length;
        AdminEntityResultsList.Append(ItemList, entities, _console, _loc);
        AdminEntityResultsList.UpdateStatus(StatusLabel, _loadedCount, hasNext, _loc);
        NextButton.Disabled = !hasNext;
    }

    public void BeginNextResultsRequest()
    {
        NextButton.Disabled = true;
    }

    private void TrySearch()
    {
        if (_timing.CurTime < _searchCooldownEnd)
            return;

        _searchCooldownEnd = _timing.CurTime + EntitySearchEuiMsg.SearchCooldown;
        UpdateSearchButton();
        SearchRequested?.Invoke();
    }

    private void UpdateSearchButton()
    {
        SearchButton.Disabled = _timing.CurTime < _searchCooldownEnd;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateSearchButton();
    }
}
