# SPDX-FileCopyrightText: 2024 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 nikitosych <boriszyn@gmail.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2026 Damian Zieliński <zientasek.pl@gmail.com>
# SPDX-FileCopyrightText: 2026 Nikita (Nick) <174215049+nikitosych@users.noreply.github.com>
# SPDX-FileCopyrightText: 2026 Polonium-bot <admin@ss14.pl>
# SPDX-FileCopyrightText: 2026 nikitosych <174215049+nikitosych@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: jobRequirementOverride
  id: Reduced
  jobs:
    Captain:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 3600 # 1 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3600 # 1 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 3600 # 1 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 3600 # 1 hour

- type: jobRequirementOverride
  id: Zeroed
  jobs:
    Captain:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 7200 #2 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 #2 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000 #10 hrs
    - !type:OverallPlaytimeRequirement
      time: 72000 #20 hrs
    HeadOfPersonnel:
    - !type:OverallPlaytimeRequirement
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 7200 #2 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 #2 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 7200 #2 hrs
    AtmosphericTechnician:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    ChiefEngineer:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 #10 hrs
    StationEngineer:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    TechnicalAssistant:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 #10 hrs
      inverted: true # stop playing intern if you're good at engineering!
    MedicalIntern:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs
      inverted: true # stop playing intern if you're good at med!
    MedicalDoctor:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    Paramedic:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    Psychologist:
    - !type:OverallPlaytimeRequirement
      time: 0
    Chemist:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    ChiefMedicalOfficer:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 10800 #3 hrs
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 10800 #3 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs
    SecurityOfficer:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 #5 hrs
    - !type:TraitsRequirement # Funky
      inverted: true
      traits:
      - Pacifist
      - Blindness
      - Muted
      - ImpairedMobility
    SecurityCadet:
    - !type:OverallPlaytimeRequirement
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 144000 #40 hrs
      inverted: true # stop playing intern if you're good at security!
    - !type:TraitsRequirement # Funky
      inverted: true
      traits:
      - Pacifist
      - Blindness
      - Muted
      - ImpairedMobility
    Brigmedic:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000 # 5 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # 5 hrs
    - !type:TraitsRequirement # Funky
      inverted: true
      traits:
      - Pacifist
      - Blindness
      - Muted
      - ImpairedMobility
    HeadOfSecurity:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 3h
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 #30 hrs
    - !type:OverallPlaytimeRequirement
      time: 72000 #20 hrs
    - !type:TraitsRequirement # Funky
      inverted: true
      traits:
      - Pacifist
      - Blindness
      - Muted
      - ImpairedMobility
    Detective:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 18000 #5 hrs
    - !type:TraitsRequirement # Funky
      inverted: true
      traits:
      - Pacifist
      - Blindness
      - Muted
      - ImpairedMobility
    Warden:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 #15 hrs
    - !type:TraitsRequirement # Funky
      inverted: true
      traits:
      - Pacifist
      - Blindness
      - Muted
      - ImpairedMobility
    ResearchAssistant:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:DepartmentTimeRequirement
      department: Science
      time: 36000 #10 hrs
      inverted: true # stop playing intern if you're good at science!
    Scientist:
    - !type:OverallPlaytimeRequirement
      time: 0
    Roboticist:
    - !type:OverallPlaytimeRequirement
      time: 0
    ResearchDirector:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 36000 #10 hrs
    Borg:
    - !type:OverallPlaytimeRequirement
      time: 18000 #5 hrs
    StationAi:
    - !type:RoleTimeRequirement
      role: JobBorg
      time: 18000 #5 hrs
    Boxer:
    - !type:OverallPlaytimeRequirement
      time: 0
    Janitor:
    - !type:OverallPlaytimeRequirement
      time: 0
    Chef:
    - !type:OverallPlaytimeRequirement
      time: 0
    Botanist:
    - !type:OverallPlaytimeRequirement
      time: 0
    Quartermaster:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 10800 #3 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 10800 #3 hrs
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hrs
    CargoTechnician:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    SalvageSpecialist:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    Bartender:
    - !type:OverallPlaytimeRequirement
      time: 0
    Chaplain:
    - !type:OverallPlaytimeRequirement
      time: 0
    Clown:
    - !type:OverallPlaytimeRequirement
      time: 0
    Mime:
    - !type:OverallPlaytimeRequirement
      time: 0
    Lawyer:
    - !type:OverallPlaytimeRequirement
      time: 0
    Librarian:
    - !type:OverallPlaytimeRequirement
      time: 0
    Musician:
    - !type:OverallPlaytimeRequirement
      time: 0
    ServiceWorker:
    - !type:OverallPlaytimeRequirement
      time: 0
    Zookeeper:
    - !type:OverallPlaytimeRequirement
      time: 0
    InternalAffairsAgent:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 10800 # 3 hours
    Magistrate:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours
    NanotrasenRepresentative:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000 # 10 hours
