// SPDX-FileCopyrightText: 2026 Maciej Walendziuk <ozzeusz@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared._Polonium.CallablePhone;
using Content.Shared.Telephone;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Polonium.CallablePhone;

[GenerateTypedNameReferences]
public sealed partial class CallablePhoneWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private SharedCallablePhoneSystem _callablePhone = default!;
    private SharedTelephoneSystem _telephone = default!;

    private EntityUid? _owner;
    private NetEntity? _selectedContact;
    private TelephoneState _currentState;
    private TelephoneState _previousState;
    private TimeSpan _buttonUnlockTime;
    private float _updateTimer;
    private const float UpdateTime = 0.25f;
    private readonly TimeSpan _buttonUnlockDelay = TimeSpan.FromSeconds(0.5f);

    public event Action<NetEntity>? CallPressed;
    public event Action? AnswerPressed;
    public event Action? HangUpPressed;

    public CallablePhoneWindow()
    {
        RobustXamlLoader.Load(this);

        AnswerCallButton.OnPressed += _ => AnswerPressed?.Invoke();
        EndCallButton.OnPressed += _ => HangUpPressed?.Invoke();
        CallButton.OnPressed += _ => OnCallPressed();

        AnswerCallButton.AddStyleClass("ButtonAccept");
        EndCallButton.AddStyleClass("Caution");

        ContactListPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(47, 47, 59) * Color.DarkGray,
            BorderColor = new Color(82, 82, 82),
            BorderThickness = new Thickness(2),
        };

        ContactListHeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(82, 82, 82),
        };

        SubtitleText.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("callable-phone-window-subtitle")));
    }

    public void InitializeDependencies(IDependencyCollection dependencies)
    {
        dependencies.InjectDependencies(this);

        _callablePhone = _entManager.System<SharedCallablePhoneSystem>();
        _telephone = _entManager.System<SharedTelephoneSystem>();
        _buttonUnlockTime = _timing.CurTime + _buttonUnlockDelay;
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }

    public void UpdateState(Dictionary<NetEntity, string> phones)
    {
        if (_owner == null || !_entManager.TryGetComponent<TelephoneComponent>(_owner.Value, out var telephone))
            return;

        if (!_entManager.TryGetComponent<CallablePhoneComponent>(_owner.Value, out var sourceCallable))
            return;

        var filteredPhones = new Dictionary<NetEntity, string>();

        foreach (var (netEntity, label) in phones)
        {
            if (!_callablePhone.IsCallablePhoneContactValid(netEntity))
                continue;

            if (!_entManager.TryGetEntity(netEntity, out var uid))
                continue;

            if (!_entManager.TryGetComponent<CallablePhoneComponent>(uid, out var callable))
                continue;

            if (!_callablePhone.CanSourceSeeInDirectory(sourceCallable, callable))
                continue;

            filteredPhones[netEntity] = label;
        }

        var callerId = _telephone.GetFormattedCallerIdForEntity(
            telephone.LastCallerId.Item1,
            telephone.LastCallerId.Item2,
            Color.LightGray,
            "Default",
            11);

        var deviceId = _telephone.GetFormattedDeviceIdForEntity(
            telephone.LastCallerId.Item3,
            Color.LightGray,
            "Default",
            11);

        CallerIdText.SetMessage(FormattedMessage.FromMarkupOrThrow(callerId));
        DeviceIdText.SetMessage(FormattedMessage.FromMarkupOrThrow(deviceId));

        var phoneArray = filteredPhones.ToArray();
        Array.Sort(phoneArray, (a, b) => string.Compare(a.Value, b.Value, StringComparison.CurrentCultureIgnoreCase));

        while (ContactsList.ChildCount > phoneArray.Length)
            ContactsList.RemoveChild(ContactsList.GetChild(ContactsList.ChildCount - 1));

        for (var i = 0; i < phoneArray.Length; i++)
        {
            var (netEntity, label) = phoneArray[i];

            if (i >= ContactsList.ChildCount)
            {
                var button = new PhoneContactButton();
                button.OnPressed += _ => SelectContact(button.NetEntity);
                ContactsList.AddChild(button);
            }

            if (ContactsList.GetChild(i) is PhoneContactButton contactButton)
            {
                contactButton.UpdateValues(netEntity, label);
                contactButton.Pressed = _selectedContact == netEntity;
            }
        }

        if (_selectedContact != null && !filteredPhones.ContainsKey(_selectedContact.Value))
            _selectedContact = null;

        UpdateAppearance();
    }

    private void SelectContact(NetEntity netEntity)
    {
        _selectedContact = netEntity;

        foreach (var child in ContactsList.Children)
        {
            if (child is PhoneContactButton button)
                button.Pressed = button.NetEntity == netEntity;
        }

        UpdateAppearance();
    }

    private void OnCallPressed()
    {
        if (_selectedContact == null)
            return;

        CallPressed?.Invoke(_selectedContact.Value);
    }

    private void UpdateAppearance()
    {
        if (_owner == null || !_entManager.TryGetComponent<TelephoneComponent>(_owner.Value, out var telephone))
            return;

        if (_currentState != telephone.CurrentState)
        {
            _previousState = _currentState;
            _currentState = telephone.CurrentState;
            _buttonUnlockTime = _timing.CurTime + _buttonUnlockDelay;
        }

        var lockButtons = _timing.CurTime < _buttonUnlockTime;
        var inCall = _currentState != TelephoneState.Idle;

        ActiveCallControlsContainer.Visible = inCall;
        CallPlacementControlsContainer.Visible = !inCall;
        CallerIdContainer.Visible = _currentState == TelephoneState.Ringing;

        FetchingContactsContainer.Visible = ContactsList.ChildCount == 0;

        foreach (var child in ContactsList.Children)
        {
            if (child is not PhoneContactButton contactButton)
                continue;

            var passesFilter = string.IsNullOrEmpty(SearchLineEdit.Text) ||
                               contactButton.Text?.Contains(SearchLineEdit.Text, StringComparison.CurrentCultureIgnoreCase) == true;

            contactButton.Visible = passesFilter;
            contactButton.Disabled = inCall || lockButtons;
        }

        switch (_currentState)
        {
            case TelephoneState.Idle:
                CallStatusText.Text = Loc.GetString("holopad-window-no-calls-in-progress");
                break;
            case TelephoneState.Calling:
                CallStatusText.Text = Loc.GetString("holopad-window-outgoing-call");
                break;
            case TelephoneState.Ringing:
                CallStatusText.Text = Loc.GetString("holopad-window-incoming-call");
                break;
            case TelephoneState.InCall:
                CallStatusText.Text = Loc.GetString("holopad-window-call-in-progress");
                break;
            case TelephoneState.EndingCall:
                CallStatusText.Text = _previousState == TelephoneState.Calling || _previousState == TelephoneState.Idle
                    ? Loc.GetString("holopad-window-call-rejected")
                    : Loc.GetString("holopad-window-call-ending");
                break;
        }

        AnswerCallButton.Disabled = _currentState != TelephoneState.Ringing || lockButtons;
        EndCallButton.Disabled = _currentState == TelephoneState.Idle || _currentState == TelephoneState.EndingCall || lockButtons;
        CallButton.Disabled = _selectedContact == null || inCall || lockButtons;
        AnswerCallButton.Visible = _currentState == TelephoneState.Ringing;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _updateTimer += args.DeltaSeconds;
        if (_updateTimer >= UpdateTime)
        {
            _updateTimer -= UpdateTime;
            UpdateAppearance();
        }
    }

    private sealed class PhoneContactButton : Button
    {
        public NetEntity NetEntity;

        public PhoneContactButton()
        {
            HorizontalExpand = true;
            SetHeight = 32;
            Margin = new Thickness(0f, 1f, 0f, 1f);
            ReservesSpace = false;
            ToggleMode = true;
        }

        public void UpdateValues(NetEntity netEntity, string label)
        {
            NetEntity = netEntity;
            Text = Loc.GetString("holopad-window-contact-label", ("label", label));
        }
    }
}
