// SPDX-FileCopyrightText: 2023 Hebi <spiritbreakz@gmail.com>
// SPDX-FileCopyrightText: 2023 Kara <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2023 Vasilis <vasilis@pikachu.systems>
// SPDX-FileCopyrightText: 2024 12rabbits <53499656+12rabbits@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 AJCM-git <60196617+AJCM-git@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Aiden <aiden@djkraz.com>
// SPDX-FileCopyrightText: 2024 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 Sk1tch <ben.peter.smith@gmail.com>
// SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
// SPDX-FileCopyrightText: 2024 Thomas <87614336+Aeshus@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Ciarán Walsh <github@ciaranwal.sh>
// SPDX-FileCopyrightText: 2025 Nikita (Nick) <174215049+nikitosych@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Polonium-bot <admin@ss14.pl>
// SPDX-FileCopyrightText: 2025 Tay <td12233a@gmail.com>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: MIT

using System.Linq;
using System.Numerics;
using Content.Client.Guidebook.RichText;
using Content.Client.UserInterface.ControlExtensions;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls.FancyTree;
using Content.Client.UserInterface.Systems.Info;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Prototypes;

namespace Content.Client.Guidebook.Controls;

[GenerateTypedNameReferences]
public sealed partial class GuidebookWindow : FancyWindow, ILinkClickHandler, IAnchorClickHandler
{
    [Dependency] private readonly DocumentParsingManager _parsingMan = default!;
    [Dependency] private readonly IResourceManager _resourceManager = default!;

    private Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> _entries = new();
    private List<ProtoId<GuideEntryPrototype>>? _rootEntries;
    private ProtoId<GuideEntryPrototype>? _forceRoot;

    private readonly ISawmill _sawmill;

    public ProtoId<GuideEntryPrototype> LastEntry;

    private readonly List<ProtoId<GuideEntryPrototype>> _openTabs = new();
    private ProtoId<GuideEntryPrototype>? _activeTabId;
    private readonly Dictionary<ProtoId<GuideEntryPrototype>, Vector2> _tabScrollPositions = new();
    private readonly Dictionary<ProtoId<GuideEntryPrototype>, string> _tabSearchTexts = new();

    private const int TabTitleMaxChars = 12;

    private bool _suppressSearchUpdate;
    private bool _suppressTreeSelectionChanged;

    public GuidebookWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = Logger.GetSawmill("Guidebook");

        Tree.DrawLines = false;
        Tree.LineWidth = 1;
        Tree.HideEmptyIcon = true;

        Tree.OnSelectedItemChanged += OnSelectionChanged;

        SearchBar.OnTextChanged += _ =>
        {
            if (_suppressSearchUpdate)
                return;

            if (_activeTabId != null)
                _tabSearchTexts[_activeTabId.Value] = SearchBar.Text ?? string.Empty;

            HandleFilter();
        };

        HomeButton.OnPressed += _ =>
        {
            var coreRuleEntry = UserInterfaceManager.GetUIController<InfoUIController>().GetCoreRuleEntry();
            if (!_entries.TryGetValue(coreRuleEntry.Id, out var entry))
                return;

            _tabScrollPositions[coreRuleEntry.Id] = Vector2.Zero;
            _tabSearchTexts[coreRuleEntry.Id] = string.Empty;

            OpenTab(entry, syncTreeSelection: true);
        };
    }

    public void HandleClick(string link)
    {
        if (!_entries.TryGetValue(link, out var entry))
            return;

        if (Tree.TryGetIndexFromMetadata(entry, out var index))
        {
            Tree.ExpandParentEntries(index.Value);
            Tree.SetSelectedIndex(index);
        }
        else
            OpenTab(entry, syncTreeSelection: false);
    }

    public void HandleAnchor(IPrototypeLinkControl prototypeLinkControl)
    {
        var prototype = prototypeLinkControl.LinkedPrototype;
        if (prototype == null)
            return;

        var (linkableControls, _) = GetLinkableControlsAndLinks(EntryContainer);
        foreach (var linkableControl in linkableControls)
        {
            if (linkableControl.RepresentedPrototype != prototype)
                continue;

            if (linkableControl is not Control control)
                return;

            if (!control.Visible)
                control.Visible = true;

            UserInterfaceManager.DeferAction(() =>
            {
                var position = control.GetControlScrollPosition();
                if (position == null)
                    return;

                Scroll.HScrollTarget = position.Value.X;
                Scroll.VScrollTarget = position.Value.Y;
            });

            break;
        }
    }

    private void OnSelectionChanged(TreeItem? item)
    {
        if (_suppressTreeSelectionChanged)
            return;

        if (item != null && item.Metadata is GuideEntry entry)
            OpenTab(entry, syncTreeSelection: false);
        else if (_openTabs.Count == 0)
            ShowEmptyState();
    }

    public void ClearSelectedGuide()
    {
        CloseAllTabs();
    }

    private void OpenTab(GuideEntry entry, bool syncTreeSelection)
    {
        if (_activeTabId != null && _activeTabId != entry.Id)
        {
            _tabScrollPositions[_activeTabId.Value] = Scroll.GetScrollValue();
            _tabSearchTexts[_activeTabId.Value] = SearchBar.Text ?? string.Empty;
        }

        if (!_openTabs.Contains(entry.Id))
            _openTabs.Add(entry.Id);

        _activeTabId = entry.Id;

        UpdateRuleNavigation(entry);

        RebuildTabHeader();

        if (syncTreeSelection)
            TrySelectTreeEntry(entry);

        ShowGuide(entry, resetScroll: false);

        var scroll = _tabScrollPositions.GetValueOrDefault(entry.Id);
        Scroll.SetScrollValue(scroll);

        var searchText = _tabSearchTexts.GetValueOrDefault(entry.Id);

        _suppressSearchUpdate = true;
        SearchBar.Text = searchText ?? string.Empty;
        _suppressSearchUpdate = false;

        HandleFilter();
    }

    private void UpdateRuleNavigation(GuideEntry entry)
    {
        var coreRulesId = UserInterfaceManager.GetUIController<InfoUIController>().RulesEntryId;
        var onCoreRulesPage = new ProtoId<GuideEntryPrototype>(entry.Id) == coreRulesId;
        ReturnContainer.Visible = entry.RuleEntry && !onCoreRulesPage;
    }

    private void TrySelectTreeEntry(GuideEntry entry)
    {
        if (!Tree.TryGetIndexFromMetadata(entry, out var index) || index == null)
            return;

        _suppressTreeSelectionChanged = true;
        Tree.ExpandParentEntries(index.Value);
        Tree.SetSelectedIndex(index.Value);
        _suppressTreeSelectionChanged = false;
    }

    private void ShowGuide(GuideEntry entry, bool resetScroll)
    {
        Placeholder.Visible = false;
        EntryContainer.Visible = true;
        EntryContainer.RemoveAllChildren();

        using var file = _resourceManager.ContentFileReadText(entry.Text);

        SearchContainer.Visible = entry.FilterEnabled;

        if (!_parsingMan.TryAddMarkup(EntryContainer, file.ReadToEnd()))
            _sawmill.Error($"Failed to parse contents of guide document {entry.Id}.");

        LastEntry = entry.Id;

        var (linkableControls, linkControls) = GetLinkableControlsAndLinks(EntryContainer);

        HashSet<IPrototype> availablePrototypeLinks = new();
        foreach (var linkableControl in linkableControls)
        {
            var prototype = linkableControl.RepresentedPrototype;
            if (prototype != null)
                availablePrototypeLinks.Add(prototype);
        }

        foreach (var linkControl in linkControls)
        {
            var prototype = linkControl.LinkedPrototype;
            if (prototype != null && availablePrototypeLinks.Contains(prototype))
                linkControl.EnablePrototypeLink();
        }

        if (resetScroll)
            Scroll.SetScrollValue(Vector2.Zero);
    }

    public void UpdateGuides(
        Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> entries,
        List<ProtoId<GuideEntryPrototype>>? rootEntries = null,
        ProtoId<GuideEntryPrototype>? forceRoot = null,
        ProtoId<GuideEntryPrototype>? selected = null)
    {
        _entries = entries;
        _rootEntries = rootEntries;
        _forceRoot = forceRoot;

        _suppressTreeSelectionChanged = true;
        RepopulateTree(rootEntries, forceRoot);
        CloseAllTabs();
        _suppressTreeSelectionChanged = false;

        Split.State = SplitContainer.SplitState.Auto;
        if (entries.Count == 1)
        {
            TreeBox.Visible = false;
            Split.ResizeMode = SplitContainer.SplitResizeMode.NotResizable;
            selected = entries.Keys.First();
        }
        else
        {
            TreeBox.Visible = true;
            Split.ResizeMode = SplitContainer.SplitResizeMode.RespectChildrenMinSize;
        }

        if (selected != null && _entries.TryGetValue(selected.Value, out var selectedEntry))
            OpenTab(selectedEntry, syncTreeSelection: true);
    }

    private IEnumerable<GuideEntry> GetSortedEntries(List<ProtoId<GuideEntryPrototype>>? rootEntries)
    {
        if (rootEntries == null)
        {
            HashSet<ProtoId<GuideEntryPrototype>> entries = new(_entries.Keys);
            foreach (var entry in _entries.Values)
                entries.ExceptWith(entry.Children);

            rootEntries = entries.ToList();
        }

        return rootEntries
            .Select(rootEntryId => _entries[rootEntryId])
            .OrderBy(rootEntry => rootEntry.Priority)
            .ThenBy(rootEntry => Loc.GetString(rootEntry.Name));
    }

    private void RepopulateTree(List<ProtoId<GuideEntryPrototype>>? roots = null,
        ProtoId<GuideEntryPrototype>? forcedRoot = null)
    {
        Tree.Clear();

        HashSet<ProtoId<GuideEntryPrototype>> addedEntries = new();

        var parent = forcedRoot == null ? null : AddEntry(forcedRoot.Value, null, addedEntries);
        foreach (var entry in GetSortedEntries(roots))
            AddEntry(entry.Id, parent, addedEntries);

        Tree.SetAllExpanded(true, 0);

        ApplyCompactTreeLayout();
    }

    private void ApplyCompactTreeLayout()
    {
        const float paddingFactor = 0.75f;
        const int rowHeight = 36;
        const int iconSize = 16;

        foreach (var item in Tree.Items)
        {
            item.Button.MinSize = new Vector2(0, rowHeight);
            item.Icon.SetSize = new Vector2(iconSize, iconSize);
            item.Icon.VerticalAlignment = VAlignment.Center;
            item.Label.VerticalAlignment = VAlignment.Center;
            item.Padding.MinWidth *= paddingFactor;
            item.Padding.VerticalAlignment = VAlignment.Center;

            if (item.Button.ChildCount > 0 && item.Button.GetChild(0) is BoxContainer row)
                row.MinHeight = rowHeight;
        }
    }

    private TreeItem? AddEntry(ProtoId<GuideEntryPrototype> id,
        TreeItem? parent,
        HashSet<ProtoId<GuideEntryPrototype>> addedEntries)
    {
        if (!_entries.TryGetValue(id, out var entry))
            return null;

        if (!addedEntries.Add(id))
        {
            _sawmill.Error($"Adding duplicate guide entry: {id}");
            return null;
        }

        var rulesProto = UserInterfaceManager.GetUIController<InfoUIController>().GetCoreRuleEntry();
        if (entry.RuleEntry && entry.Id != rulesProto.Id)
            return null;

        var item = Tree.AddItem(parent);
        item.Metadata = entry;
        item.Label.Text = Loc.GetString(entry.Name);

        foreach (var child in entry.Children)
            AddEntry(child, item, addedEntries);

        return item;
    }

    private void HandleFilter()
    {
        if (_activeTabId == null)
            return;

        if (!_entries.TryGetValue(_activeTabId.Value, out var entry) || !entry.FilterEnabled)
            return;

        if (!EntryContainer.Visible)
            return;

        var query = SearchBar.Text?.Trim() ?? string.Empty;
        foreach (var element in EntryContainer.GetSearchableControls())
            element.SetHiddenState(true, query);
    }

    private void ShowEmptyState()
    {
        Placeholder.Visible = true;
        EntryContainer.Visible = false;
        SearchContainer.Visible = false;
        ReturnContainer.Visible = false;
        EntryContainer.RemoveAllChildren();
    }

    private void CloseAllTabs()
    {
        _openTabs.Clear();
        _activeTabId = null;
        _tabScrollPositions.Clear();
        _tabSearchTexts.Clear();

        TabBar.Visible = false;
        TabsHeader.RemoveAllChildren();

        _suppressSearchUpdate = true;
        SearchBar.Text = string.Empty;
        _suppressSearchUpdate = false;

        ShowEmptyState();

        _suppressTreeSelectionChanged = true;
        Tree.SetSelectedIndex(null);
        _suppressTreeSelectionChanged = false;

        LastEntry = default;
    }

    private void RebuildTabHeader()
    {
        TabsHeader.RemoveAllChildren();

        var hasTabs = _openTabs.Count > 0;
        TabBar.Visible = hasTabs;

        if (!hasTabs)
            return;

        var canPopOut = _openTabs.Count > 1;

        foreach (var tabId in _openTabs)
        {
            if (!_entries.TryGetValue(tabId, out var entry))
                continue;

            TabsHeader.AddChild(CreateTabControl(this, entry, _activeTabId == tabId, canPopOut));
        }
    }

    private static Control CreateTabControl(GuidebookWindow window, GuideEntry entry, bool isActive, bool canPopOut)
    {
        var title = Loc.GetString(entry.Name);
        if (title.Length > TabTitleMaxChars)
            title = title.Substring(0, TabTitleMaxChars) + "...";

        var tabBackground = isActive ? Color.FromHex("#505868") : Color.FromHex("#353842");
        var accentColor = isActive ? Color.FromHex("#5B8DB8") : Color.FromHex("#3D5668");
        var textColor = isActive ? Color.White : Color.FromHex("#C8CCD4");
        var panel = new PanelContainer
        {
            MinSize = new Vector2(200, 32),
            Margin = new Thickness(0, 0, 2, 0),
            PanelOverride = new StyleBoxFlat { BackgroundColor = tabBackground },
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalExpand = true,
            SeparationOverride = 0,
        };

        row.AddChild(new PanelContainer
        {
            MinSize = new Vector2(4, 0),
            VerticalExpand = true,
            PanelOverride = new StyleBoxFlat { BackgroundColor = accentColor },
        });

        var titleButton = new ContainerButton
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            StyleBoxOverride = new StyleBoxFlat { BackgroundColor = tabBackground },
        };
        titleButton.AddChild(new Label
        {
            Text = title,
            ClipText = true,
            HorizontalExpand = true,
            Modulate = textColor,
            Margin = new Thickness(6, 0, 4, 0),
            VerticalAlignment = VAlignment.Center,
        });

        var popOutButton = new ContainerButton
        {
            MinSize = new Vector2(22, 0),
            VerticalExpand = true,
            Disabled = !canPopOut,
            StyleBoxOverride = new StyleBoxFlat { BackgroundColor = tabBackground },
            ToolTip = Loc.GetString(canPopOut
                ? "guidebook-tab-popout-tooltip"
                : "guidebook-tab-popout-disabled-tooltip"),
        };
        popOutButton.AddChild(new Label
        {
            Text = "↗",
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            Modulate = canPopOut
                ? isActive ? Color.White : Color.FromHex("#A8ADB8")
                : Color.FromHex("#5A5F6A"),
        });

        var closeButton = new ContainerButton
        {
            MinSize = new Vector2(24, 0),
            VerticalExpand = true,
            StyleBoxOverride = new StyleBoxFlat { BackgroundColor = tabBackground },
        };
        closeButton.AddChild(new Label
        {
            Text = "×",
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            Modulate = isActive ? Color.White : Color.FromHex("#A8ADB8"),
        });

        var tabId = entry.Id;
        titleButton.OnPressed += _ => window.OpenTab(entry, syncTreeSelection: true);
        popOutButton.OnPressed += _ => window.PopOutTab(tabId);
        closeButton.OnPressed += _ => window.CloseTab(tabId, syncTreeSelection: true);

        row.AddChild(titleButton);
        row.AddChild(popOutButton);
        row.AddChild(closeButton);
        panel.AddChild(row);
        return panel;
    }

    private void PopOutTab(ProtoId<GuideEntryPrototype> tabId)
    {
        if (_openTabs.Count <= 1 || !_entries.ContainsKey(tabId))
            return;

        var scroll = _activeTabId == tabId
            ? Scroll.GetScrollValue()
            : _tabScrollPositions.GetValueOrDefault(tabId);
        var search = _activeTabId == tabId
            ? SearchBar.Text ?? string.Empty
            : _tabSearchTexts.GetValueOrDefault(tabId, string.Empty);

        var newWindow = UserInterfaceManager.CreateWindow<GuidebookWindow>();
        newWindow.UpdateGuides(_entries, _rootEntries, _forceRoot, tabId);
        newWindow.ApplyPoppedTabState(tabId, scroll, search);

        newWindow.Tree.SetAllExpanded(false);
        newWindow.Tree.SetAllExpanded(true, 0);

        UserInterfaceManager.ClickSound();

        if (IsOpen)
            newWindow.Open(GlobalPosition + new Vector2(32, 32));
        else
            newWindow.OpenCenteredRight();

        CloseTab(tabId, syncTreeSelection: true);
    }

    private void ApplyPoppedTabState(ProtoId<GuideEntryPrototype> tabId, Vector2 scroll, string search)
    {
        _tabScrollPositions[tabId] = scroll;
        _tabSearchTexts[tabId] = search;

        if (_activeTabId != tabId)
            return;

        Scroll.SetScrollValue(scroll);

        _suppressSearchUpdate = true;
        SearchBar.Text = search;
        _suppressSearchUpdate = false;

        HandleFilter();
    }

    private void CloseTab(ProtoId<GuideEntryPrototype> tabId, bool syncTreeSelection)
    {
        var tabIndex = _openTabs.IndexOf(tabId);
        if (tabIndex < 0)
            return;

        var wasActive = _activeTabId == tabId;
        if (wasActive)
        {
            _tabScrollPositions[tabId] = Scroll.GetScrollValue();
            _tabSearchTexts[tabId] = SearchBar.Text ?? string.Empty;
        }

        _openTabs.RemoveAt(tabIndex);
        _tabScrollPositions.Remove(tabId);
        _tabSearchTexts.Remove(tabId);

        if (!wasActive)
        {
            RebuildTabHeader();
            return;
        }

        _activeTabId = null;
        ReturnContainer.Visible = false;

        RebuildTabHeader();

        if (_openTabs.Count == 0)
        {
            ShowEmptyState();

            if (syncTreeSelection)
            {
                _suppressTreeSelectionChanged = true;
                Tree.SetSelectedIndex(null);
                _suppressTreeSelectionChanged = false;
            }

            return;
        }

        var nextIndex = tabIndex > 0 ? tabIndex - 1 : 0;
        nextIndex = Math.Min(nextIndex, _openTabs.Count - 1);

        if (_entries.TryGetValue(_openTabs[nextIndex], out var nextEntry))
            OpenTab(nextEntry, syncTreeSelection);
    }

    private static (List<IPrototypeRepresentationControl>, List<IPrototypeLinkControl>) GetLinkableControlsAndLinks(Control parent)
    {
        List<IPrototypeRepresentationControl> linkableList = new();
        List<IPrototypeLinkControl> linkList = new();

        foreach (var child in parent.Children)
        {
            var hasChildren = child.ChildCount > 0;

            if (child is IPrototypeLinkControl linkChild)
                linkList.Add(linkChild);
            else if (child is IPrototypeRepresentationControl linkableChild)
                linkableList.Add(linkableChild);

            if (!hasChildren)
                continue;

            var (childLinkableList, childLinkList) = GetLinkableControlsAndLinks(child);

            linkableList.AddRange(childLinkableList);
            linkList.AddRange(childLinkList);
        }

        return (linkableList, linkList);
    }
}
